apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-php-config
  namespace: default
data:
  wordpress-custom.ini: |-
    file_uploads = On
    memory_limit = 128M
    upload_max_filesize = 128M
    post_max_size = 64M
    max_execution_time = 600